// Class automatically generated by Dev-C++ New Class wizard

#ifndef CGLSCENE_H
#define CGLSCENE_H
#include "cMesh.h"
#include "cExplode.h"
#include "cNode.h"
#include <list>

class cGLSL;

class cGLScene
{
 public:
  cGLScene();
  ~cGLScene();
  
  void init(int, int);
  void resize(int, int);
  void render();
  void clear(char, char, char, char, float);
  
  void reset();

  void camHorizontal(float);
  void camVertical(float);
  void camDistance(float);
  
  void addModel(const char *);
  void insert();
  void smooth();
  void unsmooth();
  void explode();
  void linemode();
  
  void draw(cMesh*);
  void draw(cMesh::Vertex*, int);
  void draw(cMesh::Vertex*, int, cMesh::Face*, int);


 private:
  struct Light
  {
    float pos[3];
    float col[3];
  };
  
  std::list<cMesh*> meshes;
  std::list<cNode*> nodes;
  std::list<cNode*> simulates;

  //camera parameters
  float q, t, d;
  float aspect;
  
  Light light;
  
  cGLSL *shader;
  
  UINT start;
  
  bool explosion;
  bool viewlines;
};

#endif // CGLSCENE_H
